apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "{{ .Values.appname }}-ingress"
  namespace: "{{ .Values.namespace }}"
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/load-balancer-name: "{{ .Values.appname }}-ingress"
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/tags: Name=alb
    alb.ingress.kubernetes.io/healthcheck-path: "/api/v1/health"
    {{- if .Values.ingress.certificateArn }}
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS": 443}]'
    alb.ingress.kubernetes.io/ssl-redirect: "443"
    alb.ingress.kubernetes.io/certificate-arn: "{{ .Values.ingress.certificateArn }}"
    {{- else }}
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}]'
    {{- end }}
spec:
  ingressClassName: alb
  rules:
    - host: "{{ .Values.ingress.domain }}"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: "{{ .Values.appname }}"
                port:
                  number: 5000
