apiVersion: v1
kind: ServiceAccount
metadata:
  name: "{{ .Values.appname }}"
  namespace: "{{ .Values.namespace }}"
  annotations:
    eks.amazonaws.com/role-arn: "{{ .Values.serviceAccount.roleArn }}"
