const formatOptions = [
  {
    description: 'email subject line',
    key: 'email_subject_line',
    title: 'Email Subject line',
  },
  {
    description: 'email content',
    key: 'email_content',
    title: 'Email Copy',
  },
  {
    description: 'call-to-action, CTA',
    key: 'cta',
    title: 'CTA',
  },
  {
    description: 'sms, chat',
    key: 'sms',
    title: 'SMS/Chat',
  },
  {
    description: 'social media',
    key: 'social_media',
    title: 'Social Media',
  },
  {
    description: 'web content',
    key: 'web_copy',
    title: 'Web Copy',
  },
];

const journeyOptions = [
  {
    key: 'Welcome',
    title: 'Welcome',
  },
  {
    key: 'Cross Sell',
    title: 'Cross Sell',
  },
  {
    key: 'Upsell',
    title: 'Upsell',
  },
  {
    key: 'End of Contract',
    title: 'End of Contract',
  },
  {
    key: 'Service',
    title: 'Service',
  },
  {
    key: 'Benefits',
    title: 'Benefits',
  },
];

const needStateOptions = [
  {
    key: 'gaming',
    title: 'Gaming',
  },
  {
    key: 'children\'s education',
    title: 'Children\'s Education',
  },
  {
    key: 'working from anywhere',
    title: 'Working from Anywhere',
  },
  {
    key: 'home is the hub',
    title: 'Home is the Hub',
  },
];

const styleOptions = [
  {
    key: 'persuasive',
    title: 'Persuasive',
  },
  {
    key: 'humourous',
    title: 'Humourous',
  },
  {
    key: 'family orientated',
    title: 'Family orientated',
  },
  {
    key: 'customer centric',
    title: 'Customer centric',
  },
  {
    key: 'urgency',
    title: 'Urgency',
  },
  {
    key: 'service-led',
    title: 'Service-led',
  },
  {
    key: 'Sale',
    title: 'Sale',
  },
];

const uspOptions = [
  {
    key: 'product features',
    title: 'Product Features',
  },
  {
    key: 'included data',
    title: 'Included Data',
  },
  {
    key: 'value',
    title: 'Value',
  },
  {
    key: 'save time',
    title: 'Save Time',
  },
  {
    key: 'save money',
    title: 'Save Money',
  },
  {
    key: 'value',
    title: 'Value',
  },
];

export const optionsMap = {
  format: ['Formats', formatOptions],
  journey: ['Journeys', journeyOptions],
  needState: ['Need States', needStateOptions],
  style: ['Styles', styleOptions],
  usp: ['USPs', uspOptions],
};

export const variationOptions = [
  {
    label: 'Format',
    value: 'format',
  },
  {
    label: 'Journey',
    value: 'journey',
  },
  {
    label: 'Need State',
    value: 'needState',
  },
  {
    label: 'Style',
    value: 'style',
  },
  {
    label: 'Unique Selling Point',
    value: 'usp',
  },
  {
    label: 'Prompt',
    value: 'prompt',
  },
];

export const frameworkOptions = [
  {
    label: 'AIDA (Attention, Interest, Desire, Action)',
    value: 'AIDA (Attention, Interest, Desire, Action)',
  },
  {
    label: 'PAS (Problem, Agitation, Solution)',
    value: 'PAS (Problem, Agitation, Solution)',
  },
  {
    label: 'FAB (Features, Advantages, Benefits)',
    value: 'FAB (Features, Advantages, Benefits)',
  },
  {
    label: '4 Ps (Promise, Picture, Proof, Push)',
    value: '4 Ps (Promise, Picture, Proof, Push)',
  },
  {
    label: 'Storytelling',
    value: 'Storytelling',
  },
  {
    label: 'Problem/Solution',
    value: 'Problem/Solution',
  },
  {
    label: 'Before/After/Bridge',
    value: 'Before/After/Bridge',
  },
  {
    label: 'The 5 Ws and H (Who, What, Where, When, Why, How)',
    value: 'The 5 Ws and H (Who, What, Where, When, Why, How)',
  },
  {
    label: 'The 4 Cs (Clear, Concise, Compelling, Credible)',
    value: 'The 4 Cs (Clear, Concise, Compelling, Credible)',
  },
  {
    label: 'The 7 Cs (Clear, Concise, Complete, Correct, Concrete, Credible, Compelling)',
    value: 'The 7 Cs (Clear, Concise, Complete, Correct, Concrete, Credible, Compelling)',
  },
];

export const imageQualityOptions = [
  {
    label: 'High Definition',
    value: 'hd',
  },
  {
    label: 'Standard',
    value: 'standard',
  },
];

export const imageResponseFormatOptions = [
  {
    label: 'Base 64 JSON',
    value: 'b64_json',
  },
  {
    label: 'URL',
    value: 'url',
  },
];

export const dalleImageSizeOptions = [
  {
    label: '256x256',
    value: '256x256',
  },
  {
    label: '512x512',
    value: '512x512',
  },
  {
    label: '1024x1024',
    value: '1024x1024',
  },
  {
    label: '1792x1024',
    value: '1792x1024',
  },
  {
    label: '1024x1792',
    value: '1024x1792',
  },
];

export const stabilityImageSizeOptions = [
  {
    label: '1024x1024',
    value: '1024x1024',
  },
  {
    label: '1152x896',
    value: '1152x896',
  },
  {
    label: '1216x832',
    value: '1216x832',
  },
  {
    label: '1344x768',
    value: '1344x768',
  },
  {
    label: '1536x640',
    value: '1536x640',
  },
  {
    label: '640x1536',
    value: '640x1536',
  },
  {
    label: '768x1344',
    value: '768x1344',
  },
  {
    label: '832x1216',
    value: '832x1216',
  },
  {
    label: '896x1152',
    value: '896x1152',
  },
];

export const imageStyleOptions = [
  {
    label: 'Natural',
    value: 'natural',
  },
  {
    label: 'Vivid',
    value: 'vivid',
  },
];

export const imageAspectRatioOptions = [
  {
    label: '16:9',
    value: '16:9',
  },
  {
    label: '1:1',
    value: '1:1',
  },
  {
    label: '21:9',
    value: '21:9',
  },
  {
    label: '2:3',
    value: '2:3',
  },
  {
    label: '3:2',
    value: '3:2',
  },
  {
    label: '4:5',
    value: '4:5',
  },
  {
    label: '5:4',
    value: '5:4',
  },
  {
    label: '9:16',
    value: '9:16',
  },
  {
    label: '9:21',
    value: '9:21',
  },
];

export const imageOutputFormatOptions = [
  {
    label: 'jpeg',
    value: 'jpeg',
  },
  {
    label: 'png',
    value: 'png',
  },
  {
    label: 'webp',
    value: 'webp',
  },
];

export const imageStylePresetOptions = [
  {
    label: '3d model',
    value: '3d-model',
  },
  {
    label: 'analog film',
    value: 'analog-film',
  },
  {
    label: 'anime',
    value: 'anime',
  },
  {
    label: 'cinematic',
    value: 'cinematic',
  },
  {
    label: 'comic book',
    value: 'comic-book',
  },
  {
    label: 'digital art',
    value: 'digital-art',
  },
  {
    label: 'enhance',
    value: 'enhance',
  },
  {
    label: 'fantasy art',
    value: 'fantasy-art',
  },
  {
    label: 'isometric',
    value: 'isometric',
  },
  {
    label: 'line art',
    value: 'line-art',
  },
  {
    label: 'low poly',
    value: 'low-poly',
  },
  {
    label: 'modeling compound',
    value: 'modeling-compound',
  },
  {
    label: 'neon punk',
    value: 'neon-punk',
  },
  {
    label: 'origami',
    value: 'origami',
  },
  {
    label: 'photographic',
    value: 'photographic',
  },
  {
    label: 'pixel art',
    value: 'pixel-art',
  },
  {
    label: 'tile texture',
    value: 'tile-texture',
  },
];

const fonts = [
  'Hershey-Plain-Simplex',
  'Helvetica-Narrow',
  'NimbusSansNarrow-Regular',
  'URWBookmanL-LighItal',
  'Adobe-Japan1-Bold-UniJIS-UTF32-H',
  'GothicBBB-Medium-78-RKSJ-H',
  'Japanese-Gothic-Regular-V',
  'Japanese-Gothic-Regular-78-RKSJ-V',
  'CharterBT-BoldItalic',
  'NimbusRomNo9L-MediItal',
  'GothicBBB-Medium-Adobe-Japan1-2',
  'HeiseiKakuGo-W5-UniJIS2004-UTF16-V',
  'HeiseiKakuGo-W5-NWP-H',
  'Japanese-Gothic-Regular-UniJIS2004-UTF16-H',
  'Hershey-Plain-Duplex-Italic',
  'GothicBBB-Medium-78-EUC-H',
  'GothicBBB-Medium-UniJIS2004-UTF8-H',
  'HeiseiKakuGo-W5-Add-V',
  'ZapfChancery-MediumItalic',
  'HeiseiKakuGo-W5-Adobe-Japan1-0',
  'Hershey-Plain',
  'Adobe-Japan1-Bold-Ext-V',
  'Helvetica-BoldOblique',
  'NimbusSansNarrow-BoldOblique',
  'URWBookmanL-DemiBold',
  'Adobe-Japan1-Bold-RKSJ-V',
  'GothicBBB-Medium-78ms-RKSJ-H',
  'CharterBT-Bold',
  'NimbusRomNo9L-ReguItal',
  'Adobe-Japan1-Bold-UniJIS2004-UTF32-V',
  'GothicBBB-Medium-V',
  'GothicBBB-Medium-UniJIS-UTF8-H',
  'HeiseiKakuGo-W5-UniJIS2004-UTF16-H',
  'Hershey-Plain-Duplex',
  'Adobe-Japan1-Bold-UniJIS-UTF32-V',
  'HeiseiKakuGo-W5-UniJIS-UCS2-HW-V',
  'GothicBBB-Medium-78ms-RKSJ-V',
  'HeiseiKakuGo-W5-83pv-RKSJ-H',
  'HeiseiKakuGo-W5-Roman',
  'Hershey-Greek-Simplex',
  'Adobe-Japan1-Bold-Ext-RKSJ-V',
  'Japanese-Gothic-Regular-H',
  'GothicBBB-Medium-UniJIS-UCS2-V',
  'Helvetica-Bold',
  'NimbusSansNarrow-Bold',
  'URWBookmanL-Ligh',
  'Japanese-Gothic-Regular-EUC-H',
  'Adobe-Japan1-Bold-UniJIS-UTF16-H',
  'Japanese-Gothic-Regular-UniJIS2004-UTF16-V',
  'HeiseiKakuGo-W5-Adobe-Japan1-4',
  'CharterBT-Italic',
  'NimbusRomNo9L-Medi',
  'Japanese-Gothic-Regular-UniJIS-UTF32-H',
  'GothicBBB-Medium-UniJIS2004-UTF16-V',
  'CIDFallBack-Identity-V',
  'Adobe-Japan1-Bold-Adobe-Japan1-6',
  'Hershey-Gothic-Italian',
  'Adobe-Japan1-Bold-Adobe-Japan1-3',
  'Japanese-Gothic-Regular-78-V',
  'GothicBBB-Medium-90msp-RKSJ-H',
  'Helvetica',
  'Japanese-Gothic-Regular-UniJISPro-UCS2-HW-V',
  'Hershey-Greek-Complex',
  'Japanese-Gothic-Regular-RKSJ-V',
  'Adobe-Japan1-Bold-Add-H',
  'HeiseiKakuGo-W5-UniJISX0213-UTF32-V',
  'Helvetica-Oblique',
  'NimbusSans-BoldItalic',
  'URWGothicL-DemiObli',
  'Japanese-Gothic-Regular-Adobe-Japan1-3',
  'Japanese-Gothic-Regular-Ext-RKSJ-H',
  'GothicBBB-Medium-UniJIS2004-UTF8-V',
  'Japanese-Gothic-Regular-90pv-RKSJ-H',
  'CharterBT-Roman',
  'NimbusRomNo9L-Regu',
  'GothicBBB-Medium-Adobe-Japan1-5',
  'Adobe-Japan1-Bold-EUC-V',
  'Adobe-Japan1-Bold-Ext-H',
  'HeiseiKakuGo-W5-UniJIS-UCS2-HW-H',
  'Hershey-Gothic-German',
  'HeiseiKakuGo-W5-Adobe-Japan1-1',
  'Hershey-Script-Simplex-Oblique',
  'Adobe-Japan1-Bold-UniJISPro-UTF8-V',
  'GothicBBB-Medium-UniJIS2004-UTF32-H',
  'Courier-BoldOblique',
  'NimbusSans-Bold',
  'URWGothicL-BookObli',
  'GothicBBB-Medium-Adobe-Japan1-0',
  'GothicBBB-Medium-UniJIS-UTF16-V',
  'HeiseiKakuGo-W5-H',
  'HeiseiKakuGo-W5-90ms-RKSJ-H',
  'D050000L',
  'HelveticaNarrow-BoldOblique',
  'Japanese-Gothic-Regular-Katakana',
  'GothicBBB-Medium-EUC-H',
  'GothicBBB-Medium-Katakana',
  'GothicBBB-Medium-RKSJ-H',
  'Hershey-Gothic-English',
  'Adobe-Japan1-Bold-Hiragana',
  'Adobe-Japan1-Bold-78-H',
  'HeiseiKakuGo-W5-WP-Symbol',
  'HeiseiKakuGo-W5-UniJIS-UTF8-H',
  'GothicBBB-Medium-78-RKSJ-V',
  'Hershey-Script-Simplex-Bold',
  'Japanese-Gothic-Regular-Ext-H',
  'Adobe-Japan1-Bold-UniJISX02132004-UTF32-V',
  'HeiseiKakuGo-W5-Add-RKSJ-H',
  'Courier-Bold',
  'NimbusMonoPS-Italic',
  'URWGothicL-Demi',
  'Japanese-Gothic-Regular-UniJIS-UCS2-H',
  'Japanese-Gothic-Regular-78-RKSJ-H',
  'HeiseiKakuGo-W5-78-RKSJ-V',
  'Japanese-Gothic-Regular-90msp-RKSJ-V',
  'Z003-MediumItalic',
  'NimbusSanL-BoldCondItal',
  'Adobe-Japan1-Bold-RKSJ-H',
  'Adobe-Japan1-Bold-Ext-RKSJ-H',
  'HeiseiKakuGo-W5-UniJISX0213-UTF32-H',
  'Cyrillic-Italic',
  'HeiseiKakuGo-W5-Hankaku',
  'HeiseiKakuGo-W5-NWP-V',
  'GothicBBB-Medium-Identity-H',
  'Japanese-Gothic-Regular-78-EUC-H',
  'Hershey-Script-Complex-Oblique',
  'HeiseiKakuGo-W5-90ms-RKSJ-V',
  'Japanese-Gothic-Regular-UniJISX0213-UTF32-H',
  'Courier-Oblique',
  'NimbusMonoPS-Regular',
  'URWGothicL-Book',
  'GothicBBB-Medium-78-V',
  'Japanese-Gothic-Regular-78-H',
  'NimbusRoman-Regular',
  'HelveticaNarrow-Oblique',
  'HeiseiKakuGo-W5-90msp-RKSJ-H',
  'Cyrillic-Regular',
  'Adobe-Japan1-Bold-78ms-RKSJ-V',
  'HeiseiKakuGo-W5-UniJISX02132004-UTF32-H',
  'Hershey-Script-Complex-Bold',
  'GothicBBB-Medium-WP-Symbol',
  'Bookman-LightItalic',
  'NimbusMonoPS-BoldItalic',
  'Japanese-Gothic-Regular-UniJIS-UTF8-V',
  'Japanese-Gothic-Regular-Roman',
  'Adobe-Japan1-Bold-V',
  'Japanese-Gothic-Regular-90ms-RKSJ-H',
  'Times-BoldItalic',
  'NimbusRoman-Italic',
  'NimbusSanL-ReguCondItal',
  'Japanese-Gothic-Regular-UniJIS-UTF8-H',
  'Adobe-Japan1-Bold-UniJIS-UCS2-H',
  'Cyrillic',
  'GothicBBB-Medium-90pv-RKSJ-H',
  'HeiseiKakuGo-W5-EUC-H',
  'Hershey-Plain-Triplex-Bold-Italic',
  'Japanese-Gothic-Regular-UniJISPro-UCS2-V',
  'Japanese-Gothic-Regular-UniJIS2004-UTF8-V',
  'GothicBBB-Medium-RKSJ-V',
  'Bookman-Light',
  'NimbusMonoPS-Bold',
  'GothicBBB-Medium-UniJISPro-UCS2-HW-V',
  'Adobe-Japan1-Bold-UniJIS2004-UTF16-V',
  'GothicBBB-Medium-UniJIS2004-UTF32-V',
  'Adobe-Japan1-Bold-NWP-H',
  'Times-Bold',
  'NimbusRoman-Bold',
  'HelveticaNarrow-Bold',
  'GothicBBB-Medium-Ext-RKSJ-V',
  'Japanese-Gothic-Regular-Adobe-Japan1-4',
  'Adobe-Japan1-Bold-Add-V',
  'Adobe-Japan1-Bold-Adobe-Japan1-0',
  'Shareware-Cyrillic-Italic',
  'HeiseiKakuGo-W5-Identity-H',
  'GothicBBB-Medium-UniJIS-UTF16-H',
  'GothicBBB-Medium-90msp-RKSJ-V',
  'HeiseiKakuGo-W5-UniJIS-UTF8-V',
  'HeiseiKakuGo-W5-Adobe-Japan1-2',
  'Hershey-Plain-Triplex-Bold',
  'HeiseiKakuGo-W5-UniJIS2004-UTF8-H',
  'Japanese-Gothic-Regular-UniJIS-UTF16-V',
  'HeiseiKakuGo-W5-78ms-RKSJ-H',
  'Bookman-DemiItalic',
  'URWBookman-Light',
  'HeiseiKakuGo-W5-Adobe-Japan1-5',
  'Adobe-Japan1-Bold-83pv-RKSJ-H',
  'Japanese-Gothic-Regular-78ms-RKSJ-H',
  'GothicBBB-Medium-Add-H',
  'Times-Italic',
  'NimbusRoman-BoldItalic',
  'NimbusSanL-BoldCond',
  'Japanese-Gothic-Regular-Hankaku',
  'Adobe-Japan1-Bold-UniJIS2004-UTF16-H',
  'Adobe-Japan1-Bold-UniJIS-UCS2-HW-V',
  'Japanese-Gothic-Regular-WP-Symbol',
  'Shareware-Cyrillic-Regular',
  'Adobe-Japan1-Bold-Roman',
  'Japanese-Gothic-Regular-UniJIS2004-UTF32-V',
  'GothicBBB-Medium-UniJIS-UTF8-V',
  'HeiseiKakuGo-W5-UniJIS-UCS2-V',
  'HeiseiKakuGo-W5-78-RKSJ-H',
  'Hershey-Plain-Duplex-Bold-Italic',
  'Japanese-Gothic-Regular-90pv-RKSJ-V',
  'GothicBBB-Medium-Ext-H',
  'Adobe-Japan1-Bold-Adobe-Japan1-4',
  'Bookman-Demi',
  'URWBookman-LightItalic',
  'HeiseiKakuGo-W5-Katakana',
  'Japanese-Gothic-Regular-Add-RKSJ-H',
  'Adobe-Japan1-Bold-UniJISX0213-UTF32-V',
  'Times-Roman',
  'StandardSymbolsPS',
  'HelveticaNarrow',
  'Japanese-Gothic-Regular-UniJISX02132004-UTF32-H',
  'HeiseiKakuGo-W5-90pv-RKSJ-H',
  'Calligraphic-Katakana',
  'Japanese-Gothic-Regular-RKSJ-H',
  'GothicBBB-Medium-Ext-V',
  'GothicBBB-Medium-UniJISPro-UTF8-V',
  'GothicBBB-Medium-90pv-RKSJ-V',
  'Hershey-Plain-Duplex-Bold',
  'Japanese-Gothic-Regular-83pv-RKSJ-H',
  'Adobe-Japan1-Bold-UniJIS-UCS2-HW-H',
  'HeiseiKakuGo-W5-UniJIS2004-UTF8-V',
  'AvantGarde-DemiOblique',
  'URWBookman-Demi',
  'Japanese-Gothic-Regular-Identity-V',
  'Japanese-Gothic-Regular-NWP-V',
  'Japanese-Gothic-Regular-78ms-RKSJ-V',
  'Palatino-BoldItalic',
  'P052-Roman',
  'NimbusSanL-ReguCond',
  'Japanese-Gothic-Regular-NWP-H',
  'GothicBBB-Medium-Hiragana',
  'HeiseiKakuGo-W5-UniJISPro-UCS2-HW-V',
  'TimesNewRoman,BoldItalic',
  'Calligraphic-Hiragana',
  'Adobe-Japan1-Bold-Adobe-Japan1-1',
  'GothicBBB-Medium-UniJISX02132004-UTF32-V',
  'HeiseiKakuGo-W5-90msp-RKSJ-V',
  'HeiseiKakuGo-W5-UniJIS2004-UTF32-H',
  'Hershey-Gothic-Italian-Oblique',
  'Japanese-Gothic-Regular-UniJISX0213-UTF32-V',
  'GothicBBB-Medium-Add-RKSJ-V',
  'Adobe-Japan1-Bold-H',
  'AvantGarde-Demi',
  'URWBookman-DemiItalic',
  'GothicBBB-Medium-UniJIS-UCS2-HW-V',
  'Adobe-Japan1-Bold-90ms-RKSJ-H',
  'GothicBBB-Medium-Ext-RKSJ-H',
  'ArtifexBullet-Identity-H',
  'Palatino-Bold',
  'P052-Italic',
  'NimbusSanL-BoldItal',
  'Adobe-Japan1-Bold-WP-Symbol',
  'GothicBBB-Medium-90ms-RKSJ-H',
  'Adobe-Japan1-Bold-UniJIS-UTF8-H',
  'TimesNewRoman,Bold',
  'URWGroteskT-Bold',
  'URWChanceryL-MediItal',
  'Japanese-Gothic-Regular-90msp-RKSJ-H',
  'Adobe-Japan1-Bold-Add-RKSJ-H',
  'HeiseiKakuGo-W5-UniJIS-UTF16-V',
  'HeiseiKakuGo-W5-UniJISPro-UCS2-V',
  'Hershey-Gothic-Italian-Bold',
  'GothicBBB-Medium-Adobe-Japan1-1',
  'Adobe-Japan1-Bold-78-RKSJ-V',
  'GothicBBB-Medium-NWP-H',
  'AvantGarde-BookOblique',
  'URWGothic-Demi',
  'GothicBBB-Medium-78-EUC-V',
  'Adobe-Japan1-Bold-UniJISX0213-UTF32-H',
  'HeiseiKakuGo-W5-78-EUC-V',
  'Palatino-Italic',
  'P052-Bold',
  'NimbusSanL-ReguItal',
  'Adobe-Japan1-Bold-Hankaku',
  'Adobe-Japan1-Bold-NWP-V',
  'Japanese-Gothic-Regular-EUC-V',
  'TimesNewRoman,Italic',
  'URWAntiquaT-RegularCondensed',
  'StandardSymL',
  'Adobe-Japan1-Bold-90ms-RKSJ-V',
  'HeiseiKakuGo-W5-Identity-V',
  'HeiseiKakuGo-W5-90pv-RKSJ-V',
  'Hershey-Gothic-German-Oblique',
  'Japanese-Gothic-Regular-Adobe-Japan1-0',
  'Japanese-Gothic-Regular-Adobe-Japan1-2',
  'HeiseiKakuGo-W5-Add-RKSJ-V',
  'AvantGarde-Book',
  'URWGothic-DemiOblique',
  'HeiseiKakuGo-W5-78-V',
  'GothicBBB-Medium-UniJIS-UCS2-H',
  'Palatino-Roman',
  'P052-BoldItalic',
  'NimbusSanL-Bold',
  'Adobe-Japan1-Bold-90msp-RKSJ-H',
  'Adobe-Japan1-Bold-UniJISX02132004-UTF32-H',
  'HeiseiKakuGo-W5-78-EUC-H',
  'TimesNewRoman',
  'Utopia-BoldItalic',
  'URWPalladioL-BoldItal',
  'HeiseiKakuGo-W5-UniJIS-UTF32-H',
  'GothicBBB-Medium-Identity-V',
  'Hershey-Gothic-German-Bold',
  'URWGothic-Book',
  'Hershey-Symbol',
  'Japanese-Gothic-Regular-UniJIS-UCS2-V',
  'NewCenturySchlbk-BoldItalic',
  'C059-Roman',
  'NimbusSanL-Regu',
  'Japanese-Gothic-Regular-Hiragana',
  'HeiseiKakuGo-W5-Ext-V',
  'Utopia-Bold',
  'URWPalladioL-Ital',
  'Japanese-Gothic-Regular-UniJIS-UTF16-H',
  'Adobe-Japan1-Bold-EUC-H',
  'Adobe-Japan1-Bold-78-RKSJ-H',
  'HeiseiKakuGo-W5-RKSJ-V',
  'Hershey-Gothic-English-SemiBold',
  'Japanese-Gothic-Regular-UniJIS-UCS2-HW-V',
  'GothicBBB-Medium-83pv-RKSJ-H',
  'Adobe-Japan1-Bold-Adobe-Japan1-2',
  'HeiseiKakuGo-W5-UniJIS2004-UTF32-V',
  'URWGothic-BookOblique',
  'Hershey-Plain-Simplex-Oblique',
  'Adobe-Japan1-Bold-UniJIS-UTF8-V',
  'GothicBBB-Medium-Roman',
  'Adobe-Japan1-Bold-UniJIS2004-UTF8-H',
  'NewCenturySchlbk-Bold',
  'C059-Italic',
  'Dingbats',
  'GothicBBB-Medium-Adobe-Japan1-3',
  'Adobe-Japan1-Bold-Identity-H',
  'HeiseiKakuGo-W5-UniJIS-UTF32-V',
  'HeiseiKakuGo-W5-Ext-RKSJ-V',
  'Utopia-Italic',
  'URWPalladioL-Bold',
  'GothicBBB-Medium-Adobe-Japan1-4',
  'Adobe-Japan1-Bold-78ms-RKSJ-H',
  'HeiseiKakuGo-W5-UniJIS-UTF16-H',
  'Hershey-Gothic-English-Oblique',
  'Adobe-Japan1-Bold-Adobe-Japan1-5',
  'GothicBBB-Medium-UniJISX0213-UTF32-V',
  'ArtifexBullet-Identity-V',
  'HeiseiKakuGo-W5-Adobe-Japan1-6',
  'HeiseiKakuGo-W5-Add-H',
  'Hershey-Plain-Simplex-Bold-Oblique',
  'HeiseiKakuGo-W5-Adobe-Japan1-3',
  'GothicBBB-Medium-78-H',
  'NewCenturySchlbk-Italic',
  'C059-BdIta',
  'CenturySchL-BoldItal',
  'Adobe-Japan1-Bold-UniJIS-UCS2-V',
  'ZapfDingbats',
  'Arial,BoldItalic',
  'Utopia-Regular',
  'URWPalladioL-Roma',
  'Japanese-Gothic-Regular-UniJIS-UTF32-V',
  'GothicBBB-Medium-UniJIS-UCS2-HW-H',
  'HeiseiKakuGo-W5-EUC-V',
  'HeiseiKakuGo-W5-Ext-H',
  'Hershey-Gothic-English-Bold',
  'Japanese-Gothic-Regular-Adobe-Japan1-6',
  'Japanese-Gothic-Regular-UniJIS2004-UTF8-H',
  'Adobe-Japan1-Bold-Katakana',
  'Hershey-Plain-Simplex-Bold',
  'Japanese-Gothic-Regular-UniJIS-UCS2-HW-H',
  'NewCenturySchlbk-Roman',
  'C059-Bold',
  'CenturySchL-Ital',
  'GothicBBB-Medium-Adobe-Japan1-6',
  'Adobe-Japan1-Bold-90pv-RKSJ-H',
  'HeiseiKakuGo-W5-UniJISPro-UTF8-V',
  'Arial,Bold',
  'Charter-BoldItalic',
  'NimbusMonL-BoldObli',
  'Japanese-Gothic-Regular-UniJISPro-UTF8-V',
  'GothicBBB-Medium-EUC-V',
  'GothicBBB-Medium-H',
  'Japanese-Gothic-Regular-Ext-V',
  'Hershey-Script-Simplex',
  'Adobe-Japan1-Bold-UniJIS2004-UTF8-V',
  'HeiseiKakuGo-W5-Hiragana',
  'Symbol',
  'HeiseiKakuGo-W5-78-H',
  'Hershey-Plain-Oblique',
  'Adobe-Japan1-Bold-UniJISPro-UCS2-HW-V',
  'GothicBBB-Medium-Add-RKSJ-H',
  'GothicBBB-Medium-Add-V',
  'Helvetica-Narrow-BoldOblique',
  'NimbusSans-Italic',
  'CenturySchL-Bold',
  'Japanese-Gothic-Regular-78-EUC-V',
  'Adobe-Japan1-Bold-90msp-RKSJ-V',
  'GothicBBB-Medium-Hankaku',
  'Arial,Italic',
  'Charter-Bold',
  'NimbusMonL-ReguObli',
  'GothicBBB-Medium-UniJISX0213-UTF32-H',
  'CIDFallBack-Identity-H',
  'Adobe-Japan1-Bold-UniJIS2004-UTF32-H',
  'Japanese-Gothic-Regular-Ext-RKSJ-V',
  'Hershey-Script-Complex',
  'Adobe-Japan1-Bold-UniJIS-UTF16-V',
  'HeiseiKakuGo-W5-RKSJ-H',
  'HeiseiKakuGo-W5-UniJISX02132004-UTF32-V',
  'HeiseiKakuGo-W5-Ext-RKSJ-H',
  'Hershey-Plain-Bold-Oblique',
  'Japanese-Gothic-Regular-UniJIS2004-UTF32-H',
  'GothicBBB-Medium-NWP-V',
  'Courier',
  'Helvetica-Narrow-Bold',
  'NimbusSans-Regular',
  'CenturySchL-Roma',
  'Japanese-Gothic-Regular-Add-RKSJ-V',
  'Japanese-Gothic-Regular-Add-H',
  'Japanese-Gothic-Regular-90ms-RKSJ-V',
  'Arial',
  'Charter-Italic',
  'NimbusMonL-Bold',
  'Japanese-Gothic-Regular-Identity-H',
  'Japanese-Gothic-Regular-Adobe-Japan1-1',
  'GothicBBB-Medium-UniJIS2004-UTF16-H',
  'GothicBBB-Medium-UniJIS-UTF32-V',
  'Hershey-Plain-Triplex-Italic',
  'GothicBBB-Medium-UniJISX02132004-UTF32-H',
  'Japanese-Gothic-Regular-Adobe-Japan1-5',
  'GothicBBB-Medium-90ms-RKSJ-V',
  'GothicBBB-Medium-UniJISPro-UCS2-V',
  'Adobe-Japan1-Bold-UniJISPro-UCS2-V',
  'Hershey-Plain-Bold',
  'Adobe-Japan1-Bold-78-EUC-V',
  'HeiseiKakuGo-W5-78ms-RKSJ-V',
  'GothicBBB-Medium-UniJIS-UTF32-H',
  'Helvetica-Narrow-Oblique',
  'NimbusSansNarrow-Oblique',
  'URWBookmanL-DemiBoldItal',
  'Adobe-Japan1-Bold-Identity-V',
  'HeiseiKakuGo-W5-V',
  'Charter-Roman',
  'NimbusMonL-Regu',
  'Adobe-Japan1-Bold-90pv-RKSJ-V',
  'Adobe-Japan1-Bold-Add-RKSJ-V',
  'Adobe-Japan1-Bold-78-V',
  'Japanese-Gothic-Regular-Add-V',
  'Hershey-Plain-Triplex',
  'HeiseiKakuGo-W5-UniJIS-UCS2-H',
  'Japanese-Gothic-Regular-UniJISX02132004-UTF32-V',
  'Adobe-Japan1-Bold-78-EUC-H',
];

fonts.sort((a, b) => a < b ? -1 : 1);
export const fontOptions = fonts.map(f => ({
  label: f,
  value: f,
}));

export const textPlacementOptions = [
  {
    label: 'top-left',
    value: 'top-left',
  },
  {
    label: 'top-center',
    value: 'top-center',
  },
  {
    label: 'top-right',
    value: 'top-right',
  },
  {
    label: 'middle-left',
    value: 'middle-left',
  },
  {
    label: 'middle-center',
    value: 'middle-center',
  },
  {
    label: 'middle-right',
    value: 'middle-right',
  },
  {
    label: 'bottom-left',
    value: 'bottom-left',
  },
  {
    label: 'bottom-center',
    value: 'bottom-center',
  },
  {
    label: 'bottom-right',
    value: 'bottom-right',
  },
];