export default {
  FILE_BUCKET: process.env.FILE_BUCKET,
  ATLASSIAN_DOMAIN: process.env.ATLASSIAN_DOMAIN,
  ATLASSIAN_USERNAME: process.env.ATLASSIAN_USERNAME,
  ATLASSIAN_API_TOKEN: process.env.ATLASSIAN_API_TOKEN,
}