apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: neo4j-vectorstore-pvc
  namespace: "{{ .Values.namespace }}"
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi