version: '3.4'

services:
  postgresql:
    image: postgres:14
    ports:
      - "5432:5432"
    restart: always
    environment:      
      POSTGRES_PASSWORD: changeme
      POSTGRES_USER: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/postgres:/var/lib/postgresql/data
      - ./docker-entrypoint-initdb.d/:/docker-entrypoint-initdb.d/

  redis:
    image: redislabs/redisearch:latest
    ports:
      - "6379:6379"
    volumes:
      - "${DOCKER_VOLUME_DIRECTORY:-.}/volumes/redis:/data:delegated"

  minio:
    image: minio/minio:RELEASE.2020-12-03T00-03-10Z
    ports:
      - "9000:9000"
    environment:
      - MINIO_ACCESS_KEY=minio
      - MINIO_SECRET_KEY=changeme
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/minio:/minio_data
    command: minio server /minio_data
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "-f",
          "http://localhost:9000/minio/health/live"
        ]
      interval: 30s
      timeout: 20s
      retries: 3

  elasticsearch:
    container_name: elasticsearch
    environment:
      - cluster.routing.allocation.disk.threshold_enabled=true
      - cluster.routing.allocation.disk.watermark.low=512mb
      - cluster.routing.allocation.disk.watermark.high=256mb
      - cluster.routing.allocation.disk.watermark.flood_stage=128mb
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms256m -Xmx256m
      - xpack.security.enabled=false
    image: elasticsearch:${ELASTICSEARCH_VERSION}
    expose:
      - 9200
    volumes:
      - /var/lib/elasticsearch/data

  temporal:
    container_name: temporal
    depends_on:
      - postgresql
      - elasticsearch
    environment:
      - DB=postgresql
      - DB_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PWD=changeme
      - POSTGRES_SEEDS=postgresql
      - DYNAMIC_CONFIG_FILE_PATH=config/dynamicconfig/development-sql.yaml
      - ENABLE_ES=true
      - ES_SEEDS=elasticsearch
      - ES_VERSION=v7
    image: temporalio/auto-setup:${TEMPORAL_VERSION}
    ports:
      - 7233:7233
    labels:
      kompose.volume.type: configMap
    volumes:
      - ./dynamicconfig:/etc/temporal/config/dynamicconfig

  temporal-admin-tools:
    container_name: temporal-admin-tools
    depends_on:
      - temporal
    environment:
      - TEMPORAL_ADDRESS=temporal:7233
      - TEMPORAL_CLI_ADDRESS=temporal:7233
    image: temporalio/admin-tools:${TEMPORAL_VERSION}
    stdin_open: true
    tty: true

  temporal-ui:
    container_name: temporal-ui
    depends_on:
      - temporal
    environment:
      - TEMPORAL_ADDRESS=temporal:7233
      - TEMPORAL_CORS_ORIGINS=http://localhost:3000
    image: temporalio/ui:${TEMPORAL_UI_VERSION}
    ports:
      - 8080:8080

  # vecsearch:
  #   container_name: vecsearch
  #   depends_on:
  #     - redis
  #     - minio
  #   env_file:
  #     - .env.vecsearch
  #   image: markmo/vecsearch:${VECSEARCH_VERSION}
  #   ports:
  #     - 5002:5002

  unstructured:
    container_name: unstructured
    image: quay.io/unstructured-io/unstructured-api:latest
    ports:
      - 8000:8000

  neo4j:
    image: neo4j:5.12.0
    ports:
      - "7474:7474"
      - "7687:7687"
    env_file:
      - ".env.neo4j"
    volumes:
      - "${DOCKER_VOLUME_DIRECTORY:-.}/volumes/neo4j/backups:/backups"
      - "${DOCKER_VOLUME_DIRECTORY:-.}/volumes/neo4j/conf:/var/lib/neo4j/conf"
      - "${DOCKER_VOLUME_DIRECTORY:-.}/volumes/neo4j/data:/data"
      - "${DOCKER_VOLUME_DIRECTORY:-.}/volumes/neo4j/import:/import"
      - "${DOCKER_VOLUME_DIRECTORY:-.}/volumes/logs:/logs"

  neo4j1:
    image: neo4j:5.12.0
    ports:
      - "7475:7474"
      - "7688:7687"
    env_file:
      - ".env.neo4j"
    volumes:
      - "${DOCKER_VOLUME_DIRECTORY:-.}/volumes/neo4j1/backups:/backups"
      - "${DOCKER_VOLUME_DIRECTORY:-.}/volumes/neo4j1/conf:/var/lib/neo4j/conf"
      - "${DOCKER_VOLUME_DIRECTORY:-.}/volumes/neo4j1/data:/data"
      - "${DOCKER_VOLUME_DIRECTORY:-.}/volumes/neo4j1/import:/import"
      - "${DOCKER_VOLUME_DIRECTORY:-.}/volumes/logs:/logs"

  # magic:
  #     image: mageai/mageai:latest
  #     command: mage start ${PROJECT_NAME}
  #     env_file:
  #       - ./backend/.env
  #     build:
  #       context: .
  #       dockerfile: ./mage/Dockerfile
  #     environment:
  #       USER_CODE_PATH: /home/src/${PROJECT_NAME}
  #       ENV: ${ENV}
  #     ports:
  #       - 6789:6789
  #     volumes:
  #       - .:/home/src/
  #     restart: on-failure:5
