apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  annotations:
  name: loki-virtualservice
  namespace: jhub
spec:
  gateways:
  - europa-standalone-gateway
  hosts:
  - loki.devsheds.io
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: loki-grafana.loki.svc.cluster.local
        port:
          number: 80
