export default {
  AWS_REGION: process.env.AWS_REGION,
  AWS_ACCESS_KEY_ID: process.env.AWS_ACCESS_KEY_ID,
  AWS_SECRET_ACCESS_KEY: process.env.AWS_SECRET_ACCESS_KEY,
  AWS_SESSION_TOKEN: process.env.AWS_SESSION_TOKEN,
  FILE_BUCKET: process.env.FILE_BUCKET,
  IMAGES_PREFIX: process.env.IMAGES_PREFIX || 'images',
  WORKSPACE_ID: process.env.WORKSPACE_ID,
  S3_ENDPOINT: process.env.S3_ENDPOINT,
  S3_PORT: process.env.S3_PORT,
  AWS_ACCESS_KEY: process.env.AWS_ACCESS_KEY,
  AWS_SECRET_KEY: process.env.AWS_SECRET_KEY,
  ENV: process.env.ENV,
  BASE_URL: process.env.BASE_URL,
}