apiVersion: v1
data:
  ENV: "prod"
  FILE_BUCKET: "{{ .Values.appname }}"
  DOCUMENTS_PREFIX: "documents"
  IMAGES_PREFIX: "images"
  PORT: "{{ .Values.port }}"
  PROJECT_NAME: "{{ .Values.appname }}"
  DISABLE_TERMINAL: "1"

  # PostgreSQL Metastore
  PGHOST: "{{ .Values.db.host }}"
  PGPORT: "5432"
  PGDATABASE: "{{ .Values.db.name }}"

  # Redis
  REDIS_HOST: "{{ .Values.redis.host }}"

  # MinIO filestore
  S3_ENDPOINT: "{{ .Values.s3.endpoint }}"
  S3_PORT: "80"

  # Background job processing
  TEMPORAL_URL: "{{ .Values.temporal.api_url }}"
  TEMPORAL_NAMESPACE: "{{ .Values.temporal.namespace }}"

  # Log aggregator
  LOKI_API_URL: "{{ .Values.loki.api_url }}"

  ########

  ## PLUGINS ########

  # Embedding plugins
  EMBEDDING_PLUGINS: ""

  # Extractor plugins
  EXTRACTOR_PLUGINS: "onesource|Onesource|./plugins/extractors/onesource,unstructured|Unstructured|./plugins/extractors/unstructured,csv|CSV Parser|./plugins/extractors/csv,json|JSON Parser|./plugins/extractors/json,neo4j|Neo4j|./plugins/extractors/neo4j,text|Text Parser|./plugins/extractors/text"

  # Feature store plugins
  FEATURE_STORE_PLUGINS: "feast|Feast|./plugins/featurestores/feast,anaml|Anaml|./plugins/featurestores/anaml"

  # Graph store plugins
  GRAPH_STORE_PLUGINS: "neo4j|Neo4j Graph Store|./plugins/graphstores/neo4j"

  # Guardrail plugins
  GUARDRAIL_PLUGINS: "pii|PII Detection|./plugins/guardrails/pii|type=input,emojiremover|Emoji Remover|./plugins/guardrails/emojiremover|type=output"

  # LLM plugins
  LLM_PLUGINS: "openai|OpenAI|./plugins/llms/openai,vertexai|VertexAI|./plugins/llms/vertexai,gpt4all|GPT4all (Private instance)|./plugins/llms/gpt4all,localai|LocalAI (Private instance)|./plugins/llms/localai,llama2|Llama 2 (Private instance)|./plugins/llms/llama2,llamaapi|Llama API|./plugins/llms/llamaapi,bedrock|AWS Bedrock|./plugins/llms/bedrock,sentenceencoder|Google Universal Sentence Encoder|./plugins/llms/sentenceencoder"

  # Loader plugins
  LOADER_PLUGINS: "api|API Loader|./plugins/loaders/api,minio|MinIO Document Loader|./plugins/loaders/minio,wikipedia|Wikipedia Loader|./plugins/loaders/wikipedia"

  # Model Provider plugins
  MODEL_PROVIDER_PLUGINS: "huggingface|Huggingface|./plugins/modelproviders/huggingface"

  # Output Parser plugins
  OUTPUT_PARSER_PLUGINS: "numberedlist|Numbered List|./plugins/outputparsers/numberedlist,list|Inline List|./plugins/outputparsers/list,json|Parse or fix JSON|./plugins/outputparsers/json,boolean|Boolean|./plugins/outputparsers/boolean,datetime|DateTime|./plugins/outputparsers/datetime,action|Action|./plugins/outputparsers/action"

  # Passport auth plugins
  PASSPORT_PLUGINS: "localapikey|Local API Key|./plugins/passport/localapikey,keycloakbearer|Keycloak Bearer|./plugins/passport/keycloak"

  # SQL source plugins
  SQL_SOURCE_PLUGINS: "postgresql|PostgreSQL|./plugins/sqlsources/postgresql,clickhouse|ClickHouse|./plugins/sqlsources/clickhouse,bigquery|BigQuery|./plugins/sqlsources/bigquery"

  # Tool plugins
  TOOL_PLUGINS: "serpapi|SerpAPI|./plugins/tools/serpapi,calculator|Calculator|./plugins/tools/calculator,weather|Weather|./plugins/tools/openweather,email|Email|./plugins/tools/email,cypher|Cypher|./plugins/tools/cypher,bigquery|BigQuery|./plugins/tools/bigquery,playwright_screenshot|Playwright Screenshot|./plugins/tools/playwright_screenshot"

  # Vector store plugins
  VECTOR_STORE_PLUGINS: "redis|Redis Vector Store|./plugins/vectorstores/redis,neo4j|Neo4j Vector Store|./plugins/vectorstores/neo4j"

  ########

  ## PLUGIN SETTINGS ########

  ## Feature store plugins ########

  # Anaml
  ANAML_API_URL: "{{ .Values.anaml.api_url }}"

  ########

  ## Graph store plugins ########

  # Neo4j
  NEO4J_HOST: "{{ .Values.graph_stores.neo4j.host }}"
  NEO4J_PORT: "{{ .Values.graph_stores.neo4j.port }}"

  ########

  ## Guardrail plugins ########

  # PII Guardrail
  EUROPA_PII_API_URL: "{{ .Values.custom_models.europa_pii_api_url }}"
  HUGGINGFACE_PII_API_URL: "{{ .Values.huggingface.pii_api_url }}"

  ########

  ## Loader plugins ########

  # Onesource
  ONESOURCE_API_URL: "{{ .Values.onesource.api_url }}"

  # Unstructured
  UNSTRUCTURED_API_URL: "{{ .Values.unstructured.api_url }}"

  ########

  ## Model provider plugins ########

  # Huggingface
  HUGGINGFACE_BASE_URL: "{{ .Values.huggingface.base_url }}"
  HUGGINGFACE_HUB_API: "{{ .Values.huggingface.hub_url }}"

  ########

  ## LLM plugins ########

  # Bedrock - ./plugins/llms/bedrock
  AWS_REGION: "{{ .Values.bedrock.region }}"

  # gpt4all - ./plugins/llms/gpt4all
  GPT4ALL_API: "{{ .Values.gpt4all.api_url }}"

  # Llama 2 - ./plugins/llms/llama2
  LLAMA2_BASE_PATH: "{{ .Values.llama2.base_path }}"

  # Llama API - ./plugins/llms/llamaapi
  LLAMAAPI_BASE_PATH: "{{ .Values.llamaapi.base_path }}"

  # LocalAI - ./plugins/llms/localai
  LOCALAI_BASE_PATH: "{{ .Values.localai.base_path }}"

  # OpenAI - ./plugins/llms/openai

  # Vertex AI - ./plugins/llms/vertexai
  PALM2_MODEL_NAME: "{{ .Values.google_vertex.palm2_default_model }}"

  ########

  ## Passport auth plugins ########

  # Keycloak - ./plugins/passport/keycloak
  KEYCLOAK_HOST: "{{ .Values.keycloak.host }}"
  KEYCLOAK_CALLBACK: "{{ .Values.keycloak.callback }}"
  KEYCLOAK_REALM: "{{ .Values.keycloak.realm }}"
  KEYCLOAK_CLIENT_ID: "{{ .Values.keycloak.client_id }}"

  # localapikey - ./plugins/passport/localapikey
  TOKEN_STORE_KEY: "onetoks"

  ########

  ## Tool plugins ########

  # SERP API - ./plugins/tools/serpapi
  SERPAPI_URL: "{{ .Values.serpapi.api_url }}"

  # OpenWeather - ./plugins/tools/openweather

  # Mailtrap - ./plugins/tools/email
  MAILTRAP_TEMPLATE_UUID: "{{ .Values.mailtrap.template_uuid }}"

  ########

  ## Vector store plugins ########

  # Neo4j
  NEO4J_VECTOR_STORE_HOST: "{{ .Values.vector_stores.neo4j.host }}"
  NEO4J_VECTOR_STORE_PORT: "{{ .Values.vector_stores.neo4j.port }}"

  # Redis
  SEARCH_API: "{{ .Values.vecsearch.api_url }}"

  NEO4J_AUTH: "neo4j/changeme"
  NEO4J_server_memory_pagecache_size: "1G"
  NEO4J_server_memory_heap_initial__size: "1G"
  NEO4J_server_memory_heap_max__size: "2G"
  NEO4J_PLUGINS: '["apoc", "graph-data-science"]'
  NEO4J_dbms_security_procedures_unrestricted: "gds.*,apoc.*"
  NEO4J_dbms_security_procedures_allowlist: "gds.*,apoc.*"
  NEO4J_dbms_memory_transaction_total_max: "0"
  NEO4J_apoc_trigger_enabled: "true"
  NEO4J_dbms_routing_enabled: "true"
  NEO4J_ACCEPT_LICENSE_AGREEMENT: "yes"
  NEO4J_apoc_export_file_enabled: "true"
  NEO4J_apoc_import_file_enabled: "true"
  NEO4J_server_config_strict__validation_enabled: "false"

  ########

kind: ConfigMap
metadata:
  name: "{{ .Values.appname }}"
  namespace: "{{ .Values.namespace }}"
