apiVersion: v1
kind: Service
metadata:
  name: neo4j-graphstore
  namespace: "{{ .Values.namespace }}"
spec:
  ports:
    - name: "7474"
      port: 7474
      targetPort: 7474
    - name: "7687"
      port: 7687
      targetPort: 7687
  selector:
    app: neo4j-graphstore