apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Values.appname }}"
  namespace: "{{ .Values.namespace }}"
type: Opaque
stringData:
  # PostgreSQL Metastore
  PGUSER: "{{ .Values.db.user }}"
  PGPASSWORD: "{{ .Values.db.pass }}"

  # Redis
  REDIS_PASSWORD: "{{ .Values.redis.pass }}"

  # MinIO filestore
  AWS_ACCESS_KEY: "{{ .Values.s3.access_key }}"
  AWS_SECRET_KEY: "{{ .Values.s3.secret_key }}"

  ########

  ## PLUGIN SETTINGS ########

  ## Feature store plugins ########

  # Anaml
  ANAML_API_KEY: "{{ .Values.anaml.api_key }}"
  ANAML_API_SECRET: "{{ .Values.anaml.api_secret }}"

  ########

  ## Graph store plugins ########

  # Neo4j
  NEO4J_USERNAME: "{{ .Values.graph_stores.neo4j.username }}"
  NEO4J_PASSWORD: "{{ .Values.graph_stores.neo4j.password }}"

  ########

  ## Model provider plugins ########

  # Huggingface
  HUGGINGFACE_TOKEN: "{{ .Values.huggingface.token }}"

  ########

  ## LLM plugins ########

  # Bedrock - ./plugins/llms/bedrock
  AWS_ACCESS_KEY_ID: "{{ .Values.bedrock.access_key_id }}"
  AWS_SECRET_ACCESS_KEY: "{{ .Values.bedrock.secret_access_key }}"
  AWS_SESSION_TOKEN: "{{ .Values.bedrock.session_token }}"

  # gemini - ./plugins/llms/gemini
  GOOGLE_APPLICATION_CREDENTIALS: "{{ .Values.gemini.service_account_key_file }}"

  # Llama API - ./plugins/llms/llamaapi
  LLAMAAPI_API_KEY: "{{ .Values.llamaapi.api_key }}"

  # Mistral - ./plugins/llms/mistral
  MISTRAL_API_KEY: "{{ .Values.mistral.api_key }}"

  # OpenAI - ./plugins/llms/openai
  OPENAI_API_KEY: "{{ .Values.openai.api_key }}"

  # Vertex AI - ./plugins/llms/vertexai
  GOOGLE_API_KEY: "{{ .Values.google_vertex.api_key }}"

  ########

  ## Passport auth plugins ########

  # Keycloak - ./plugins/passport/keycloak
  KEYCLOAK_CLIENT_SECRET: "{{ .Values.keycloak.client_secret }}"

  # localapikey - ./plugins/passport/localapikey
  PROMPTSTORE_API_KEY: "{{ .Values.system_api_key }}"

  ########

  ## SQL sources ########

  ## BigQuery
  PROJECT_ID: "{{ .Values.bigquery.project_id }}"
  KEY_FILENAME: "{{ .Values.bigquery.key_filename }}"

  ########

  ## Tool plugins ########

  # Jira - ./plugins/tools/jira
  JIRA_EMAIL: "{{ .Values.jira.email }}"
  JIRA_PAT: "{{ .Values.jira.pat }}"

  # Mailtrap - ./plugins/tools/email
  MAILTRAP_TOKEN: "{{ .Values.mailtrap.token }}"
  SENDER_EMAIL: "{{ .Values.mailtrap.sender_email }}"
  PROMPTSTORE_EMAIL: "{{ .Values.promptstore.email }}"
  MAILTRAP_TEMPLATE_UUID: "{{ .Values.mailtrap.template_uuid }}"
  MAILTRAP_INVITE_TEMPLATE_UUID: "{{ .Values.mailtrap.invite_template_uuid }}"

  # OpenWeather - ./plugins/tools/openweather
  OPENWEATHER_API_KEY: "{{ .Values.openweather.api_key }}"

  # SERP API - ./plugins/tools/serpapi
  SERPAPI_KEY: "{{ .Values.serpapi.api_key }}"

  ########

  ## Vector store plugins ########

  # Chroma
  CHROMA_TOKEN: "{{ .Values.vector_stores.chroma.token }}"

  # Neo4j
  NEO4J_VECTOR_STORE_USERNAME: "{{ .Values.vector_stores.neo4j.username }}"
  NEO4J_VECTOR_STORE_PASSWORD: "{{ .Values.vector_stores.neo4j.password }}"

  ########

  EMAIL_OVERRIDE: "{{ .Values.promptstore.email }}"