apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Values.appname }}"
  namespace: "{{ .Values.namespace }}"
type: Opaque
stringData:
  # postgresql metastore
  PGUSER: "{{ .Values.db.user }}"
  PGPASSWORD: "{{ .Values.db.pass }}"

  # redis
  REDIS_PASSWORD: "{{ .Values.redis.pass }}"

  # minio filestore
  AWS_ACCESS_KEY: "{{ .Values.s3.access_key }}"
  AWS_SECRET_KEY: "{{ .Values.s3.secret_key }}"

  ########

  ## PLUGIN SETTINGS ########

  ## feature store plugins ########

  # anaml
  ANAML_API_KEY: "{{ .Values.anaml.api_key }}"
  ANAML_API_SECRET: "{{ .Values.anaml.api_secret }}"

  ########

  ## Model provider plugins ########

  # Huggingface
  HUGGINGFACE_TOKEN: "{{ .Values.huggingface.token }}"

  ########

  ## LLM plugins ########

  # OpenAI - ./plugins/llms/openai
  OPENAI_API_KEY: "{{ .Values.openai.api_key }}"

  # Vertex AI - ./plugins/llms/vertexai
  GOOGLE_API_KEY: "{{ .Values.google_vertex.api_key }}"

  ########

  ## Passport auth plugins ########

  # keycloak - ./plugins/passport/keycloak
  KEYCLOAK_CLIENT_SECRET: "{{ .Values.keycloak.client_secret }}"

  # localapikey - ./plugins/passport/localapikey
  PROMPTSTORE_API_KEY: "{{ .Values.promptstore.api_key }}"

  ########

  ## Tool plugins ########

  # SERP API - ./plugins/tools/serpapi
  SERPAPI_KEY: "{{ .Values.serpapi.api_key }}"

  # OpenWeather - ./plugins/tools/openweather
  OPENWEATHER_API_KEY: "{{ .Values.openweather.api_key }}"

  # Mailtrap - ./plugins/tools/email
  MAILTRAP_TEMPLATE_UUID: "{{ .Values.mailtrap.template_uuid }}"
  MAILTRAP_TOKEN: "{{ .Values.mailtrap.token }}"
  SENDER_EMAIL: "{{ .Values.mailtrap.sender_email }}"
  PROMPTSTORE_EMAIL: "{{ .Values.promptstore_email }}"

  ########
