apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.appname }}"
  namespace: "{{ .Values.namespace }}"
spec:
  type: NodePort
  selector:
    app: api
  ports:
    - name: "5000"
      port: 5000
