apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: "{{ .Values.appname }}-virtualservice"
  namespace: "{{ .Values.ingress.virtualservice_namespace }}"
spec:
  hosts:
    - "{{ .Values.appname }}.{{ .Values.ingress.domain }}"
  gateways:
    - "{{ .Values.ingress.gateway }}"
  http:
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            host: "{{ .Values.appname }}.{{ .Values.namespace }}.svc.cluster.local"
            port:
              number: 5000
