export default {
  FILE_BUCKET: process.env.FILE_BUCKET,
  GOOGLE_DRIVE_CLIENT_ID: process.env.GOOGLE_DRIVE_CLIENT_ID,
  GOOGLE_DRIVE_CLIENT_SECRET: process.env.GOOGLE_DRIVE_CLIENT_SECRET,
  GOOGLE_DRIVE_REDIRECT_URL: process.env.GOOGLE_DRIVE_REDIRECT_URL,
}