export default {
  NEO4J_HOST: process.env.NEO4J_VECTOR_STORE_HOST,
  NEO4J_PORT: process.env.NEO4J_VECTOR_STORE_PORT,
  NEO4J_USERNAME: process.env.NEO4J_VECTOR_STORE_USERNAME,
  NEO4J_PASSWORD: process.env.NEO4J_VECTOR_STORE_PASSWORD,
}