module.exports = {
  KEYCLOAK_CALLBACK: process.env.KEYCLOAK_CALLBACK,
  KEYCLOAK_CLIENT_ID: process.env.KEYCLOAK_CLIENT_ID,
  KEYCLOAK_CLIENT_SECRET: process.env.KEYCLOAK_CLIENT_SECRET,
  KEYCLOAK_HOST: process.env.KEYCLOAK_HOST,
  KEYCLOAK_REALM: process.env.KEYCLOAK_REALM,
}